resolver: lts-18.21
packages:
  - '.'
extra-deps:
  - servant-multipart-0.12.1
  - quickcheck-arbitrary-adt-0.3.1.0
  - esqueleto-3.5.3.0
  - persistent-2.13.2.1
  - mtl-2.2.2
  - persistent-template-2.12.0.0
  - persistent-postgresql-2.13.2.1
  - katip-0.8.7.0
  - say-0.1.0.1
  - monad-logger-0.3.36
  - safe-exceptions-0.1.7.2
  - wai-extra-3.1.8
  - fast-logger-3.0.5@sha256:fd430f998045aa86226faa29652ee797410a11edd9b77b709be1bedc96f77c4d,2398
  - safe-0.3.19
  - wai-middleware-metrics-0.2.4
  - resource-pool-0.2.3.2
  - microlens-0.4.12.0
  - servant-auth-server-0.4.6.0
  - servant-auth-0.4.0.0
  - servant-server-0.18.3
  - servant-0.18.3
  - servant-client-0.18.3
  - servant-client-core-0.18.3
  - servant-docs-0.11.9
  - servant-foreign-0.15.4
  - cryptonite-0.28@sha256:b6c75e62b4c655d4cb1bcbb80d01430d136aac32bd6962c86c84738935cc8f9d,18195
  - password-3.0.0.0
  - password-types-1.0.0.0
  - password-instances-3.0.0.0
